# Codebase Translator Configuration

# Agent configurations
# You can use any OpenAI-compatible model or OpenRouter models:
# - "gpt-4" or "claude-3-5-sonnet-20241022" for OpenAI/Anthropic
# - "openrouter/meta-llama/llama-3.1-8b-instruct" for OpenRouter
# - "openrouter/anthropic/claude-3.5-sonnet" for OpenRouter

project_analyzer:
  model_name: "openrouter/qwen/qwen3-coder-30b-a3b-instruct"
  temperature: 0.0

architecture_translator:
  model_name: "openrouter/qwen/qwen3-coder-30b-a3b-instruct"
  temperature: 0.0

traverser:
  model_name: "openrouter/qwen/qwen3-coder-30b-a3b-instruct"
  temperature: 0.0

documenter:
  model_name: "openrouter/qwen/qwen3-coder-30b-a3b-instruct"
  temperature: 0.0

translator:
  model_name: "openrouter/qwen/qwen3-coder-30b-a3b-instruct"
  temperature: 0.1

# Workflow settings
output_path: "translated"

# Rate Limiting Configuration
rate_limiting:
  max_concurrent_requests: 2  # Reduce concurrent API calls
  requests_per_minute: 10     # Limit total requests per minute
  batch_delay_seconds: 2      # Delay between batches
  retry_delay_seconds: 5      # Initial retry delay (exponential backoff)
  max_retries: 3              # Maximum retry attempts
  max_tokens_per_request: 2000  # Limit output tokens per request

# PostgreSQL Database Configuration (Optional)
postgres:
  enabled: false  # Set to true to enable PostgreSQL persistence
  url: "postgresql://username:password@localhost:5432/codebase_translator"
  min_connections: 5
  max_connections: 20
  initialize_schema: true
  schema_file: "src/persistence/schema_simple.sql"

# File processing settings
max_file_size: 1048576  # 1MB in bytes
supported_extensions:
  - ".py"
  - ".js"
  - ".ts" 
  - ".java"
  - ".go"
  - ".rs"
  - ".cpp"
  - ".c"

ignore_patterns:
  - "__pycache__"
  - ".git"
  - "node_modules"
  - ".venv"
  - "venv"
  - "dist"
  - "build"
  - "*.pyc"
  - "*.pyo"

# Language-specific settings (Optional)
language_settings:
  python:
    include_type_hints: true
    format_with_black: false

  javascript:
    use_es6: true
    include_jsdoc: false

  typescript:
    strict_mode: true
    include_interfaces: true

  java:
    package_structure: true
    include_javadoc: false
